concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  check_code_style:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      name: Download google-java-format 1.9
      run: 'curl -L -o $HOME/google-java-format.jar https://github.com/google/google-java-format/releases/download/v1.15.0/google-java-format-1.15.0-all-deps.jar

        curl -L -o $HOME/google-java-format-diff.py https://raw.githubusercontent.com/google/google-java-format/v1.15.0/scripts/google-java-format-diff.py

        chmod +x $HOME/google-java-format-diff.py

        '
    - continue-on-error: true
      name: Check Java formatting
      run: "base_branch=\"${{ github.event.pull_request.base.ref }}\"\necho \"Running\
        \ google-java-format-diff against 'origin/$base_branch'\"\ngit fetch origin\
        \ \"$base_branch\" --depth 1\ndiff=$(git diff -U0 $(git merge-base HEAD origin/$base_branch)\
        \ | $HOME/google-java-format-diff.py --google-java-format-jar=$HOME/google-java-format.jar\
        \ -p1)\nif [[ $diff ]]; then\n  echo \"Please run google-java-format on the\
        \ changes in this pull request\"\n  git diff -U0 $(git merge-base HEAD origin/$base_branch)\
        \ | $HOME/google-java-format-diff.py --google-java-format-jar=$HOME/google-java-format.jar\
        \ -p1\n  exit 1\nfi\n"
    - continue-on-error: true
      name: Check Kotlin formatting
      run: './gradlew spotlessCheck

        '
    - continue-on-error: true
      name: Check Kotlin Quality
      run: './gradlew detekt

        '
name: Check Code Style
on:
  repository_dispatch:
    types: trigger-ga___check_code_style.yml
permissions:
  contents: read
