concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  run_aggregateDocs:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Run aggregateDocs
      run: ./gradlew clean aggregateDocs --parallel
  run_instrumentAll:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Run :preinstrumented:instrumentAll
      run: ./gradlew :preinstrumented:instrumentAll
    - continue-on-error: true
      name: Run :preinstrumented:instrumentAll with SDK 33
      run: PREINSTRUMENTED_SDK_VERSIONS=33 ./gradlew :preinstrumented:instrumentAll
    - continue-on-error: true
      name: Run :preinstrumented:publishToMavenLocal with SDK 33
      run: PREINSTRUMENTED_SDK_VERSIONS=33 PUBLISH_PREINSTRUMENTED_JARS=true ./gradlew
        :preinstrumented:publishToMavenLocal
  run_javadocJar:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Run javadocJar
      run: ./gradlew clean javadocJar --parallel
  run_publishToMavenLocal:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Publish to Maven local
      run: ./gradlew publishToMavenLocal --no-watch-fs
name: Gradle Tasks Validation
on:
  repository_dispatch:
    types: trigger-ga___gradle_tasks_validation.yml
permissions:
  contents: read
