concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  validation:
    name: Validation
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: gradle/actions/wrapper-validation@v3
name: Validate Gradle Wrapper
on:
  repository_dispatch:
    types: trigger-ga___gradle_wrapper_validation.yml
permissions:
  contents: read
