concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  graphics_tests:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: adopt
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Show runner info
      run: 'uname -a

        '
    - continue-on-error: true
      env:
        SKIP_ERRORPRONE: true
        SKIP_JAVADOC: true
      name: Run unit tests
      run: './gradlew :integration_tests:nativegraphics:testDebugUnitTest --info --stacktrace
        --continue --parallel --no-watch-fs "-Drobolectric.alwaysIncludeVariantMarkersInTestName=true"
        "-Dorg.gradle.workers.max=2"

        '
    - continue-on-error: true
      if: always()
      name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test_results_${{ matrix.device }}
        path: '**/build/test-results/**/TEST-*.xml

          **/roborazzi/build/reports/*

          **/roborazzi/src/screenshots/*

          **/roborazzi/build/outputs/roborazzi/*

          '
    strategy:
      matrix:
        device:
        - macos-13
        - macos-14
        - ubuntu-22.04
        - windows-2022
name: Graphics Tests
on:
  repository_dispatch:
    types: trigger-ga___graphics_tests.yml
permissions:
  contents: read
